//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace AutoCheckMechanical.Services.DocumentOutput {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ITF_O_S_DOCUMENT_OUTPUTBinding", Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class ITF_O_S_DOCUMENT_OUTPUTService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ITF_O_S_DOCUMENT_OUTPUTOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ITF_O_S_DOCUMENT_OUTPUTService() {
            this.Url = "http://brjgs916:50000/sap/xi/engine?type=entry&version=3.0&Sender.Service=ED0_604&Interface=http%3A%2F%2Fsoa.weg.net%2F70%2Fpp%2FDocumentOutput%2Fsender%5EITF_O_S_DOCUMENT_OUTPUT";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ITF_O_S_DOCUMENT_OUTPUTCompletedEventHandler ITF_O_S_DOCUMENT_OUTPUTCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("MTP_DOCUMENT_OUTPUT_R", Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
        public DTP_DOCUMENT_OUTPUT_R ITF_O_S_DOCUMENT_OUTPUT([System.Xml.Serialization.XmlElementAttribute(Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")] DTP_DOCUMENT_OUTPUT MTP_DOCUMENT_OUTPUT) {
            object[] results = this.Invoke("ITF_O_S_DOCUMENT_OUTPUT", new object[] {
                        MTP_DOCUMENT_OUTPUT});
            return ((DTP_DOCUMENT_OUTPUT_R)(results[0]));
        }
        
        /// <remarks/>
        public void ITF_O_S_DOCUMENT_OUTPUTAsync(DTP_DOCUMENT_OUTPUT MTP_DOCUMENT_OUTPUT) {
            this.ITF_O_S_DOCUMENT_OUTPUTAsync(MTP_DOCUMENT_OUTPUT, null);
        }
        
        /// <remarks/>
        public void ITF_O_S_DOCUMENT_OUTPUTAsync(DTP_DOCUMENT_OUTPUT MTP_DOCUMENT_OUTPUT, object userState) {
            if ((this.ITF_O_S_DOCUMENT_OUTPUTOperationCompleted == null)) {
                this.ITF_O_S_DOCUMENT_OUTPUTOperationCompleted = new System.Threading.SendOrPostCallback(this.OnITF_O_S_DOCUMENT_OUTPUTOperationCompleted);
            }
            this.InvokeAsync("ITF_O_S_DOCUMENT_OUTPUT", new object[] {
                        MTP_DOCUMENT_OUTPUT}, this.ITF_O_S_DOCUMENT_OUTPUTOperationCompleted, userState);
        }
        
        private void OnITF_O_S_DOCUMENT_OUTPUTOperationCompleted(object arg) {
            if ((this.ITF_O_S_DOCUMENT_OUTPUTCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ITF_O_S_DOCUMENT_OUTPUTCompleted(this, new ITF_O_S_DOCUMENT_OUTPUTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUT {
        
        private string userCodeField;
        
        private DTP_DOCUMENT_OUTPUTDMS dMSField;
        
        private string languageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCode {
            get {
                return this.userCodeField;
            }
            set {
                this.userCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DTP_DOCUMENT_OUTPUTDMS DMS {
            get {
                return this.dMSField;
            }
            set {
                this.dMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUTDMS {
        
        private DTP_ORDER_BY_LIST2OrderBy[] orderByListField;
        
        private DTP_DOCUMENT_OUTPUTDMSDocument documentField;
        
        private DTP_INDEX indexField;
        
        private DTP_DOCUMENT_OUTPUTDMSOriginals originalsField;
        
        private bool returnClassInfoField;
        
        private string getObjectLinksField;
        
        private bool returnCurrentVersionField;
        
        private System.DateTime validFromField;
        
        private bool validFromFieldSpecified;
        
        private System.DateTime validToField;
        
        private bool validToFieldSpecified;
        
        private bool returnDocumentStructureField;
        
        private DTP_DOCUMENT_OUTPUTDMSSearchBy searchByField;
        
        public DTP_DOCUMENT_OUTPUTDMS() {
            this.getObjectLinksField = "X";
            this.returnCurrentVersionField = false;
            this.returnDocumentStructureField = false;
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("OrderBy", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DTP_ORDER_BY_LIST2OrderBy[] OrderByList {
            get {
                return this.orderByListField;
            }
            set {
                this.orderByListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DTP_DOCUMENT_OUTPUTDMSDocument Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DTP_INDEX Index {
            get {
                return this.indexField;
            }
            set {
                this.indexField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DTP_DOCUMENT_OUTPUTDMSOriginals Originals {
            get {
                return this.originalsField;
            }
            set {
                this.originalsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ReturnClassInfo {
            get {
                return this.returnClassInfoField;
            }
            set {
                this.returnClassInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DefaultValueAttribute("X")]
        public string GetObjectLinks {
            get {
                return this.getObjectLinksField;
            }
            set {
                this.getObjectLinksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ReturnCurrentVersion {
            get {
                return this.returnCurrentVersionField;
            }
            set {
                this.returnCurrentVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime ValidFrom {
            get {
                return this.validFromField;
            }
            set {
                this.validFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidFromSpecified {
            get {
                return this.validFromFieldSpecified;
            }
            set {
                this.validFromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime ValidTo {
            get {
                return this.validToField;
            }
            set {
                this.validToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidToSpecified {
            get {
                return this.validToFieldSpecified;
            }
            set {
                this.validToFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.ComponentModel.DefaultValueAttribute(false)]
        public bool ReturnDocumentStructure {
            get {
                return this.returnDocumentStructureField;
            }
            set {
                this.returnDocumentStructureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DTP_DOCUMENT_OUTPUTDMSSearchBy SearchBy {
            get {
                return this.searchByField;
            }
            set {
                this.searchByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_ORDER_BY_LIST2OrderBy {
        
        private string fieldField;
        
        private string sequenceField;
        
        private string sortField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Field {
            get {
                return this.fieldField;
            }
            set {
                this.fieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string Sequence {
            get {
                return this.sequenceField;
            }
            set {
                this.sequenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Sort {
            get {
                return this.sortField;
            }
            set {
                this.sortField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUT_R {
        
        private DTP_ERRORS_RError[] errorListField;
        
        private string userCodeField;
        
        private DTP_DOCUMENT_OUTPUT_RDIR[] dIRListField;
        
        private string languageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DTP_ERRORS_RError[] ErrorList {
            get {
                return this.errorListField;
            }
            set {
                this.errorListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UserCode {
            get {
                return this.userCodeField;
            }
            set {
                this.userCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DIR", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DTP_DOCUMENT_OUTPUT_RDIR[] DIRList {
            get {
                return this.dIRListField;
            }
            set {
                this.dIRListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_ERRORS_RError {
        
        private string codeField;
        
        private string tYPEField;
        
        private DTP_ERRORS_RErrorDescription[] descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TYPE {
            get {
                return this.tYPEField;
            }
            set {
                this.tYPEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Description", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DTP_ERRORS_RErrorDescription[] Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_ERRORS_RErrorDescription {
        
        private string languageField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUT_RDIR {
        
        private string documentNumberField;
        
        private string typeField;
        
        private string partField;
        
        private string versionField;
        
        private string designOfficeField;
        
        private DTP_DOCUMENT_HEADER templateField;
        
        private string statusField;
        
        private string changeNumberField;
        
        private DTP_DOCUMENT_HEADER superiorDocumentField;
        
        private System.DateTime validFromField;
        
        private bool validFromFieldSpecified;
        
        private System.DateTime validToField;
        
        private bool validToFieldSpecified;
        
        private DTP_DOCUMENT_OUTPUT_RDIROriginal[] originalsField;
        
        private DTP_DOCUMENT_OUTPUT_RDIRDescriptionList descriptionListField;
        
        private DTP_DOCUMENT_OUTPUT_RDIRObjectLinks objectLinksField;
        
        private bool returnClassificationField;
        
        private DTP_DOCUMENT_OUTPUT_RDIRClassification classificationField;
        
        private DTP_DOCUMENT_OUTPUT_RDIRDocumentStructure[] documentStructureListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocumentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Part {
            get {
                return this.partField;
            }
            set {
                this.partField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DesignOffice {
            get {
                return this.designOfficeField;
            }
            set {
                this.designOfficeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DTP_DOCUMENT_HEADER Template {
            get {
                return this.templateField;
            }
            set {
                this.templateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ChangeNumber {
            get {
                return this.changeNumberField;
            }
            set {
                this.changeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DTP_DOCUMENT_HEADER SuperiorDocument {
            get {
                return this.superiorDocumentField;
            }
            set {
                this.superiorDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime ValidFrom {
            get {
                return this.validFromField;
            }
            set {
                this.validFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidFromSpecified {
            get {
                return this.validFromFieldSpecified;
            }
            set {
                this.validFromFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date")]
        public System.DateTime ValidTo {
            get {
                return this.validToField;
            }
            set {
                this.validToField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValidToSpecified {
            get {
                return this.validToFieldSpecified;
            }
            set {
                this.validToFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Original", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DTP_DOCUMENT_OUTPUT_RDIROriginal[] Originals {
            get {
                return this.originalsField;
            }
            set {
                this.originalsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DTP_DOCUMENT_OUTPUT_RDIRDescriptionList DescriptionList {
            get {
                return this.descriptionListField;
            }
            set {
                this.descriptionListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DTP_DOCUMENT_OUTPUT_RDIRObjectLinks ObjectLinks {
            get {
                return this.objectLinksField;
            }
            set {
                this.objectLinksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ReturnClassification {
            get {
                return this.returnClassificationField;
            }
            set {
                this.returnClassificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DTP_DOCUMENT_OUTPUT_RDIRClassification Classification {
            get {
                return this.classificationField;
            }
            set {
                this.classificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DocumentStructure", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DTP_DOCUMENT_OUTPUT_RDIRDocumentStructure[] DocumentStructureList {
            get {
                return this.documentStructureListField;
            }
            set {
                this.documentStructureListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_HEADER {
        
        private string documentNumberField;
        
        private string typeField;
        
        private string partField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocumentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Part {
            get {
                return this.partField;
            }
            set {
                this.partField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUT_RDIROriginal {
        
        private string pathField;
        
        private string descriptionField;
        
        private string codeField;
        
        private string storageCategoryField;
        
        private string applicationCodeField;
        
        private bool checkInField;
        
        private string checkedOutUserField;
        
        private string uRLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string StorageCategory {
            get {
                return this.storageCategoryField;
            }
            set {
                this.storageCategoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ApplicationCode {
            get {
                return this.applicationCodeField;
            }
            set {
                this.applicationCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool CheckIn {
            get {
                return this.checkInField;
            }
            set {
                this.checkInField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CheckedOutUser {
            get {
                return this.checkedOutUserField;
            }
            set {
                this.checkedOutUserField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUT_RDIRDescriptionList {
        
        private DTP_DOCUMENT_OUTPUT_RDIRDescriptionListDescription descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DTP_DOCUMENT_OUTPUT_RDIRDescriptionListDescription Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUT_RDIRDescriptionListDescription {
        
        private string languageField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUT_RDIRObjectLinks {
        
        private DTP_DOCUMENT_OUTPUT_RDIRObjectLinksWBSElement[] wBSElementListField;
        
        private string[] masterMaterialListField;
        
        private string[] claimListField;
        
        private DTP_DOCUMENT_OUTPUT_RDIRObjectLinksDocumentInfo[] documentInfoListField;
        
        private DTP_DOCUMENT_OUTPUT_RDIRObjectLinksPurchaseOrder[] purchaseOrderListField;
        
        private string[] equipmentListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("WBSElement", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DTP_DOCUMENT_OUTPUT_RDIRObjectLinksWBSElement[] WBSElementList {
            get {
                return this.wBSElementListField;
            }
            set {
                this.wBSElementListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MasterMaterialNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] MasterMaterialList {
            get {
                return this.masterMaterialListField;
            }
            set {
                this.masterMaterialListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Claim", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] ClaimList {
            get {
                return this.claimListField;
            }
            set {
                this.claimListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DocumentInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DTP_DOCUMENT_OUTPUT_RDIRObjectLinksDocumentInfo[] DocumentInfoList {
            get {
                return this.documentInfoListField;
            }
            set {
                this.documentInfoListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("PurchaseOrder", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DTP_DOCUMENT_OUTPUT_RDIRObjectLinksPurchaseOrder[] PurchaseOrderList {
            get {
                return this.purchaseOrderListField;
            }
            set {
                this.purchaseOrderListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("EquipmentNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] EquipmentList {
            get {
                return this.equipmentListField;
            }
            set {
                this.equipmentListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUT_RDIRObjectLinksWBSElement {
        
        private string wBSElementKeyField;
        
        private string versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WBSElementKey {
            get {
                return this.wBSElementKeyField;
            }
            set {
                this.wBSElementKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUT_RDIRObjectLinksDocumentInfo {
        
        private string documentNumberField;
        
        private string documentTypeField;
        
        private string documentPartField;
        
        private string documentVersionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocumentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocumentPart {
            get {
                return this.documentPartField;
            }
            set {
                this.documentPartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocumentVersion {
            get {
                return this.documentVersionField;
            }
            set {
                this.documentVersionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUT_RDIRObjectLinksPurchaseOrder {
        
        private string purchasingDocumentNumberField;
        
        private string itemNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PurchasingDocumentNumber {
            get {
                return this.purchasingDocumentNumberField;
            }
            set {
                this.purchasingDocumentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemNumber {
            get {
                return this.itemNumberField;
            }
            set {
                this.itemNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUT_RDIRClassification {
        
        private string classTypeField;
        
        private DTP_DOCUMENT_OUTPUT_RDIRClassificationClass[] classListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ClassType {
            get {
                return this.classTypeField;
            }
            set {
                this.classTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Class", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DTP_DOCUMENT_OUTPUT_RDIRClassificationClass[] ClassList {
            get {
                return this.classListField;
            }
            set {
                this.classListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUT_RDIRClassificationClass {
        
        private string classNumberField;
        
        private DTP_DOCUMENT_OUTPUT_RDIRClassificationClassCharacteristic[] characteristicListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ClassNumber {
            get {
                return this.classNumberField;
            }
            set {
                this.classNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Characteristic", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DTP_DOCUMENT_OUTPUT_RDIRClassificationClassCharacteristic[] CharacteristicList {
            get {
                return this.characteristicListField;
            }
            set {
                this.characteristicListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUT_RDIRClassificationClassCharacteristic {
        
        private string nameField;
        
        private string[] valueListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] ValueList {
            get {
                return this.valueListField;
            }
            set {
                this.valueListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUT_RDIRDocumentStructure {
        
        private string itemField;
        
        private string documentNumberField;
        
        private string documentTypeField;
        
        private string documentPartField;
        
        private string documentVersionField;
        
        private decimal quantityField;
        
        private bool quantityFieldSpecified;
        
        private string sortStringField;
        
        private string quantityIsFixedField;
        
        private string cADIndicatorField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocumentNumber {
            get {
                return this.documentNumberField;
            }
            set {
                this.documentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocumentPart {
            get {
                return this.documentPartField;
            }
            set {
                this.documentPartField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DocumentVersion {
            get {
                return this.documentVersionField;
            }
            set {
                this.documentVersionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuantitySpecified {
            get {
                return this.quantityFieldSpecified;
            }
            set {
                this.quantityFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SortString {
            get {
                return this.sortStringField;
            }
            set {
                this.sortStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string QuantityIsFixed {
            get {
                return this.quantityIsFixedField;
            }
            set {
                this.quantityIsFixedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CADIndicator {
            get {
                return this.cADIndicatorField;
            }
            set {
                this.cADIndicatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_INDEX {
        
        private string fromField;
        
        private string toField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string From {
            get {
                return this.fromField;
            }
            set {
                this.fromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string To {
            get {
                return this.toField;
            }
            set {
                this.toField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUTDMSDocument {
        
        private string statusField;
        
        private string userField;
        
        private string designOfficeField;
        
        private DTP_DOCUMENT_HEADER superiorDocumentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string User {
            get {
                return this.userField;
            }
            set {
                this.userField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DesignOffice {
            get {
                return this.designOfficeField;
            }
            set {
                this.designOfficeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DTP_DOCUMENT_HEADER SuperiorDocument {
            get {
                return this.superiorDocumentField;
            }
            set {
                this.superiorDocumentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUTDMSOriginals {
        
        private bool checkInField;
        
        private string pathField;
        
        private bool uRLField;
        
        private bool uRLFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool CheckIn {
            get {
                return this.checkInField;
            }
            set {
                this.checkInField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Path {
            get {
                return this.pathField;
            }
            set {
                this.pathField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool URL {
            get {
                return this.uRLField;
            }
            set {
                this.uRLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool URLSpecified {
            get {
                return this.uRLFieldSpecified;
            }
            set {
                this.uRLFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUTDMSSearchBy {
        
        private DTP_DOCUMENT_OUTPUTDMSSearchByHeader headerField;
        
        private DTP_DOCUMENT_OUTPUTDMSSearchByDocument documentField;
        
        private DTP_DOCUMENT_OUTPUTDMSSearchByObjectLinks objectLinksField;
        
        private DTP_DOCUMENT_OUTPUTDMSSearchByClassification classificationField;
        
        private DTP_DOCUMENT_OUTPUTDMSSearchByCharacteristic characteristicField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DTP_DOCUMENT_OUTPUTDMSSearchByHeader Header {
            get {
                return this.headerField;
            }
            set {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DTP_DOCUMENT_OUTPUTDMSSearchByDocument Document {
            get {
                return this.documentField;
            }
            set {
                this.documentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DTP_DOCUMENT_OUTPUTDMSSearchByObjectLinks ObjectLinks {
            get {
                return this.objectLinksField;
            }
            set {
                this.objectLinksField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DTP_DOCUMENT_OUTPUTDMSSearchByClassification Classification {
            get {
                return this.classificationField;
            }
            set {
                this.classificationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DTP_DOCUMENT_OUTPUTDMSSearchByCharacteristic Characteristic {
            get {
                return this.characteristicField;
            }
            set {
                this.characteristicField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUTDMSSearchByHeader {
        
        private DTP_DOCUMENT_HEADER[] headerInfoListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Document", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DTP_DOCUMENT_HEADER[] HeaderInfoList {
            get {
                return this.headerInfoListField;
            }
            set {
                this.headerInfoListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUTDMSSearchByDocument {
        
        private string[] descriptionListField;
        
        private string[] changeNumberListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Description", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] DescriptionList {
            get {
                return this.descriptionListField;
            }
            set {
                this.descriptionListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ChangeNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] ChangeNumberList {
            get {
                return this.changeNumberListField;
            }
            set {
                this.changeNumberListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUTDMSSearchByObjectLinks {
        
        private string[] materialListField;
        
        private string[] claimListField;
        
        private string[] wBSElementListField;
        
        private DTP_DOCUMENT_OUTPUTDMSSearchByObjectLinksPOItem[] pOItemListField;
        
        private DTP_DOCUMENT_HEADER[] documentInfoRecordListField;
        
        private string[] equipmentListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("MaterialNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] MaterialList {
            get {
                return this.materialListField;
            }
            set {
                this.materialListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("ClaimNotificationNo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] ClaimList {
            get {
                return this.claimListField;
            }
            set {
                this.claimListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("WBSElementKey", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] WBSElementList {
            get {
                return this.wBSElementListField;
            }
            set {
                this.wBSElementListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("POItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DTP_DOCUMENT_OUTPUTDMSSearchByObjectLinksPOItem[] POItemList {
            get {
                return this.pOItemListField;
            }
            set {
                this.pOItemListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("DocumentInfoRecord", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DTP_DOCUMENT_HEADER[] DocumentInfoRecordList {
            get {
                return this.documentInfoRecordListField;
            }
            set {
                this.documentInfoRecordListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("EquipmentNumber", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] EquipmentList {
            get {
                return this.equipmentListField;
            }
            set {
                this.equipmentListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUTDMSSearchByObjectLinksPOItem {
        
        private string purchasingDocumentNumberField;
        
        private string itemNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PurchasingDocumentNumber {
            get {
                return this.purchasingDocumentNumberField;
            }
            set {
                this.purchasingDocumentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemNumber {
            get {
                return this.itemNumberField;
            }
            set {
                this.itemNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUTDMSSearchByClassification {
        
        private string classTypeField;
        
        private DTP_DOCUMENT_OUTPUTDMSSearchByClassificationClass[] classListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ClassType {
            get {
                return this.classTypeField;
            }
            set {
                this.classTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Class", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DTP_DOCUMENT_OUTPUTDMSSearchByClassificationClass[] ClassList {
            get {
                return this.classListField;
            }
            set {
                this.classListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUTDMSSearchByClassificationClass {
        
        private string classNumberField;
        
        private DTP_DOCUMENT_OUTPUTDMSSearchByClassificationClassCharacteristic[] characteristicListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ClassNumber {
            get {
                return this.classNumberField;
            }
            set {
                this.classNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Characteristic", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DTP_DOCUMENT_OUTPUTDMSSearchByClassificationClassCharacteristic[] CharacteristicList {
            get {
                return this.characteristicListField;
            }
            set {
                this.characteristicListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUTDMSSearchByClassificationClassCharacteristic {
        
        private string nameField;
        
        private string[] valueListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] ValueList {
            get {
                return this.valueListField;
            }
            set {
                this.valueListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUTDMSSearchByCharacteristic {
        
        private string classTypeField;
        
        private DTP_DOCUMENT_OUTPUTDMSSearchByCharacteristicCharacteristic[] characteristicListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ClassType {
            get {
                return this.classTypeField;
            }
            set {
                this.classTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Characteristic", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public DTP_DOCUMENT_OUTPUTDMSSearchByCharacteristicCharacteristic[] CharacteristicList {
            get {
                return this.characteristicListField;
            }
            set {
                this.characteristicListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4161.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://soa.weg.net/70/pp/DocumentOutput/sender")]
    public partial class DTP_DOCUMENT_OUTPUTDMSSearchByCharacteristicCharacteristic {
        
        private string nameField;
        
        private string[] valueListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] ValueList {
            get {
                return this.valueListField;
            }
            set {
                this.valueListField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    public delegate void ITF_O_S_DOCUMENT_OUTPUTCompletedEventHandler(object sender, ITF_O_S_DOCUMENT_OUTPUTCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4161.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ITF_O_S_DOCUMENT_OUTPUTCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ITF_O_S_DOCUMENT_OUTPUTCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DTP_DOCUMENT_OUTPUT_R Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DTP_DOCUMENT_OUTPUT_R)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591